[Distribution]
Distribution=alma
Release=10

[Output]
Format=disk
OutputDirectory=mkosi.output
ImageId=alma

[Content]
Bootable=true
Bootloader=systemd-boot
UnifiedKernelImages=yes
SplitArtifacts=yes
Packages=
        systemd
        systemd-udev
        dbus
        podman
        systemd-networkd