[Distribution]
Distribution=alma
Release=10
Repositories=epel

[Output]
Format=disk
OutputDirectory=mkosi.output
ImageId=alma
SplitArtifacts=yes

[Content]
RootPassword=root
Bootable=true
Packages=
    kernel
    systemd
    systemd-udev
    systemd-boot
    systemd-boot-unsigned
    systemd-ukify
    systemd-networkd
    systemd-resolved
    dbus
    podman
    cryptsetup
    firewalld
    iproute
    iputils
RemovePackages=
    dnf
    dnf-data
    dnf-plugins-core
    rpm
    yum
KernelCommandLine=
    logo.nologo
    quiet
CleanPackageMetadata=yes
Locale=C.UTF-8
WithDocs=no