[Output]
Format=cpio
CompressOutput=zstd

[Content]
Initrds=
Bootable=no
<<<<<<< HEAD:mkosi.images/initrd/mkosi..conf
Packages=
    systemd
    systemd-udev
    util-linux
    kmod
    coreutils
    cryptsetup
=======
MakeInitrd=yes
CleanPackageMetadata=yes
ExtraTrees=mkosi.initrd
>>>>>>> parent of 81661f1 (Restructure initrd image config):mkosi.initrd.conf
