[Output]
OutputDirectory=mkosi.output

[Distribution]
Distribution=fedora
Release=44
#Repositories=epel

[Build]
Environment='SYSTEMD_REPART_MKFS_OPTIONS_EROFS=-z lz4hc'

[Output]
Format=disk
OutputDirectory=mkosi.output
ImageId=alma
SplitArtifacts=uki,partitions
CompressOutput=zstd
CompressLevel=4
Output=%i_%v_%a

[Config]
Dependencies=initrd

[Content]
Initrds=%O/initrd_%v_%a
UnifiedKernelImageFormat=%i_%v_%a
Hostname=particle
RootPassword=root
Bootable=true
Packages=
    # Core & Kernel
    kernel
    kmod
    coreutils
    util-linux
    ca-certificates
    e2fsprogs
    xfsprogs
    procps-ng
    dosfstools
    efibootmgr

    # Systemd & UKI Infrastructure
    systemd-udev
    systemd-boot-unsigned
    systemd-ukify
    systemd-networkd
    systemd-networkd-defaults
    systemd-resolved
    systemd-container

    # Security, SELinux & Firewalls
    cryptsetup
    firewalld
    container-selinux
    libselinux-utils
    policycoreutils
    selinux-policy-targeted

    # Networking & Remote Access
    iproute
    iputils
    wireguard-tools
    openssh
    openssh-server
    curl

    # Containers & IPC
    dbus-broker
    podman

    # Shell, Editors & Admin Utilities
    bat
    fish
    jq
    less
    nano
    tar
    unzip
    vim
    zip
    zstd
VolatilePackages=
        systemd
        udev
RemovePackages=
    dnf
    dnf-data
    dnf-plugins-core
    yum
    dracut
KernelCommandLine=
    logo.nologo
    systemd.machine_id=firmware
    lsm=selinux
    enforcing=0
    console=ttyS0,115200n8
    rd.systemd.break=pre-mount
    rd.systemd.debug_shell
    rd.systemd.default_debug_tty=ttyS0
    rd.debug systemd.log_level=debug
    systemd.log_target=console
CleanPackageMetadata=yes
Locale=C.UTF-8
WithDocs=no