# Enable the universe repository for access to a wider range of packages.
# Ubuntu repositories: main (default), universe, restricted, multiverse
# To enable additional repos, add them as comma-separated values.

[Match]
Distribution=ubuntu

[Distribution]
Repositories=universe
