[Distribution]
Distribution=alma
Release=10

[Output]
Format=cpio
CompressOutput=zstd

[Content]
Bootable=no
Packages=
    systemd
    systemd-udev
    util-linux
    kmod
    coreutils
    cryptsetup