# Docker system extension
#
# This sysext adds Docker to the base Ubuntu image.
# Only files added on top of the base are included in the extension.

[Config]
Dependencies=base

[Distribution]
Distribution=ubuntu
Release=noble
Repositories=universe

[Output]
Format=sysext
Overlay=yes

[Content]
BaseTrees=%O/base
Packages=
        docker.io
        docker-compose-v2
