#!/bin/sh
set -eu

if mountpoint -q /sysroot/var; then
    upper=/sysroot/var/etc
    work=/sysroot/var/.etc-work
else
    upper=/run/etc-upper
    work=/run/etc-work
fi

mkdir -p "$upper" "$work"

mount -t overlay overlay \
    -o "lowerdir=/sysroot/etc,upperdir=$upper,workdir=$work" \
    /sysroot/etc