[Partition]
Type=root
Format=erofs
Label=root_%A
ReadOnly=yes
Verity=data
VerityMatchKey=root

# Tell systemd-repart to populate the filesystem from the mkosi rootfs tree
CopyFiles=/

# Sizing
SizeMinBytes=500M
SizeMaxBytes=2G

MakeSymlinks=
    /home:var/home
    /root:var/roothome
    /opt:var/opt
    /srv:var/srv
    /usr/local:var/usrlocal