[Partition]
Type=root
Format=erofs
Label=root_%A
ReadOnly=yes
Verity=data
VerityMatchKey=root

# Tell systemd-repart to populate the filesystem from the mkosi rootfs tree
CopyFiles=/

# Sizing
SizeMinBytes=1G
SizeMaxBytes=2G