[Partition]
Type=var
Format=xfs
Label=var
SizeMinBytes=5G
GrowFileSystem=yes
Encrypt=key-file

# Directory paths must be absolute relative to the partition root
MakeDirectories=/home /opt /adm /cache /db /empty /ftp /games /kerberos /lib /local /lock /log /mail /nis /preserve /run /spool /tmp /yp /roothome /usrlocal /etc