[Output]
Format=disk
ImageId=alma
SplitArtifacts=yes

[Content]
Initrds=initrd
RootPassword=root
Bootable=true
Packages=
    kernel
    systemd
    systemd-libs
    systemd-pam
    systemd-udev
    systemd-boot
    systemd-boot-unsigned
    systemd-ukify
    systemd-networkd
    systemd-networkd-defaults
    systemd-resolved
    # This is needed for sd-sysupdate to pull updates
    systemd-container
    dbus
    openssh
    openssh-server
    podman
    cryptsetup
    firewalld
    iproute
    iputils
    curl
    libcurl-minimal
    vim
    nano
    less
    selinux-policy-targeted
    policycoreutils
    libselinux-utils
RemovePackages=
    dnf
    dnf-data
    dnf-plugins-core
    yum
    dracut
KernelCommandLine=
    logo.nologo
    quiet
    systemd.machine_id=firmware
    lsm=selinux
    enforcing=0
CleanPackageMetadata=yes
Locale=C.UTF-8
WithDocs=no