[Source]
Type=url-file
Path=https://github.com/ta-vroom/ubuntu-mkosi/releases/download/@v/
MatchPattern=alma_@v.efi

[Target]
Type=regular-file
Path=/efi/EFI/Linux
MatchPattern=alma_@v+@l-@d.efi
InstancesMax=2
Mode=0755