name: Build

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on: 
  workflow_dispatch:
  #push:

jobs:
  CreateImage:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v4

      - name: Set current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Builds per Diem
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ env.DATE }}-${{ github.run_id }}
          restore-keys: |
            ${{ env.DATE }}-

      - name: Cache APT Packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-apt-
      
      - name: Increment count
        run: |
          COUNT=1
          if [ -f builds ]; then
            COUNT=$(( $(cat builds) + 1 ))
          fi
          echo "$COUNT" > builds
          echo "Current count is: $(cat builds)"
          echo "RELEASE_TAG=${DATE}-${COUNT}" >> $GITHUB_ENV
      
      - name: Install Dependencies
        run: |
          sudo sed -i 's|azure\.archive\.ubuntu\.com|archive\.ubuntu\.com|g' /etc/apt/sources.list /etc/apt/sources.list.d/*.sources 2>/dev/null || true
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update
          
          PACKAGES=(mkosi systemd-boot systemd-repart systemd-ukify python3-pefile binutils mtools dosfstools erofs-utils)
          
          sudo apt-get install -d -y "${PACKAGES[@]}"
          sudo apt-get install -y "${PACKAGES[@]}"

          # Clean obsolete debs
          sudo apt-get autoclean
     
      - name: Build OS Image
        run: |
          printf "%s" "${{ env.RELEASE_TAG }}" > mkosi.version
          sudo SYSTEMD_REPART_MKFS_OPTIONS_EROFS="-z zstd" mkosi build mkosi build --unified-kernel-image-format="alma_${{ env.RELEASE_TAG }}"
          
      - name: Sign and generate SHA256SUMS
        env:
          GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_KEY" | gpg --batch --import
          
          sudo chown -R runner:runner ./mkosi.output

          VER="${{ env.RELEASE_TAG }}"
          
          mv ./mkosi.output/alma_${VER}.efi .
          mv ./mkosi.output/alma_${VER}.raw .
          mv ./mkosi.output/alma_${VER}.root-x86-64.raw .
          mv ./mkosi.output/alma_${VER}.root-x86-64-verity.raw .

          sha256sum alma_${VER}.* > SHA256SUMS
          
          gpg --batch --yes --pinentry-mode loopback \
              --passphrase "$GPG_PASSPHRASE" \
              --detach-sign --armor --output SHA256SUMS.gpg SHA256SUMS

      - name: Clean-up Releases
        run: | 
          # Delete all pre-releases
          gh release list -L 500 --json tagName,isPrerelease --jq '[.[] | select(.isPrerelease)][0:][].tagName' | xargs -r -I {} gh release delete {} --cleanup-tag -y

      - name: Publish GitHub Release Artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "${{ env.RELEASE_TAG }}"
          prerelease: false
          files: |
            ./alma_*.efi
            ./alma_*.raw
            SHA256SUMS
            SHA256SUMS.gpg
