name: Build

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on: 
  workflow_dispatch:
  #push:

jobs:
  build_release:
    name: Build Image
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7

      - name: Set current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Cache APT Packages
        uses: actions/cache@v6
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-apt-
      
      - name: Release Tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          DATE="${{ env.DATE }}"

          LATEST_NUM=$(gh release list --limit 100 --exclude-drafts --json tagName --jq '.[].tagName' \
            | tr -d '\r' \
            | sed -nE "s/^${DATE}$/0/p; s/^${DATE}\.([0-9]+)$/\1/p" \
            | sort -n \
            | tail -n 1)

          # Ensure LATEST_NUM is strictly digits; otherwise treat as empty
          if [[ ! "$LATEST_NUM" =~ ^[0-9]+$ ]]; then
            LATEST_NUM=""
          fi

          if [ -z "$LATEST_NUM" ]; then
            RELEASE_TAG="${DATE}"
          else
            RELEASE_TAG="${DATE}.$(( 10#$LATEST_NUM + 1 ))"
          fi

          echo "RELEASE_TAG=${RELEASE_TAG}" >> "$GITHUB_ENV"
          echo "Generated tag: ${RELEASE_TAG}"
          
      - name: setup-mkosi
        uses: systemd/mkosi@v27

      # - name: Install Dependencies
      #   run: |
      #     sudo sed -i 's|azure\.archive\.ubuntu\.com|archive\.ubuntu\.com|g' /etc/apt/sources.list /etc/apt/sources.list.d/*.sources 2>/dev/null || true
      #     sudo rm -rf /var/lib/apt/lists/*
      #     sudo apt-get update
          
      #     PACKAGES=(mkosi systemd-boot systemd-repart systemd-ukify python3-pefile binutils mtools dosfstools erofs-utils)
          
      #     sudo apt-get install -d -y "${PACKAGES[@]}"
      #     sudo apt-get install -y "${PACKAGES[@]}"

      #     # Clean obsolete debs
      #     sudo apt-get autoclean

      - name: Build initrd
        run: |
          sudo mkosi --image initrd build

      - name: Build OS Image
        run: |
          printf "%s" "${{ env.RELEASE_TAG }}" > mkosi.version
          sudo mkosi build --unified-kernel-image-format="alma_${{ env.RELEASE_TAG }}" --debug

      - name: List files
        run: |
          ls -la ./mkosi.output
          ls -la 
      - name: Sign and generate SHA256SUMS
        env:
          GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_KEY" | gpg --batch --import
          
          sudo chown -R runner:runner ./mkosi.output

          VER="${{ env.RELEASE_TAG }}"
          
          mv ./mkosi.output/alma_${VER}.efi .
          mv ./mkosi.output/alma_${VER}.raw .
          mv ./mkosi.output/alma_${VER}.root-x86-64.raw .
          mv ./mkosi.output/alma_${VER}.root-x86-64-verity.raw .

          sha256sum alma_${VER}.* > SHA256SUMS
          
          gpg --batch --yes --pinentry-mode loopback \
              --passphrase "$GPG_PASSPHRASE" \
              --detach-sign --armor --output SHA256SUMS.gpg SHA256SUMS

      - name: Clean-up Releases
        run: | 
          # Delete all pre-releases
          gh release list -L 500 --json tagName,isPrerelease --jq '[.[] | select(.isPrerelease)][0:][].tagName' | xargs -r -I {} gh release delete {} --cleanup-tag -y

      - name: Publish GitHub Release Artifacts
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "${{ env.RELEASE_TAG }}"
          prerelease: false
          files: |
            ./alma_*.efi
            ./alma_*.raw
            SHA256SUMS
            SHA256SUMS.gpg

      - name: Cache packages
        run: |
          sudo chown -R runner:runner /var/cache/apt/archives