name: CacheTest

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on: 
  workflow_dispatch:
  #push:

jobs:
  cache-test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache counter
        uses: actions/cache@v4
        with:
          path: nummer
          key: nummer-${{ github.run_id }}
          restore-keys: |
            nummer-
      - name: Increment count
        run: |
          COUNT=1
          if [ -f nummer ]; then
            COUNT=$(( $(cat nummer) + 1 ))
          fi
          echo "$COUNT" > nummer
          echo "Current count is: $(cat nummer)"