name: ShellTest

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on: 
  workflow_dispatch:
  #push:

jobs:
  cache-test:
    runs-on: ubuntu-latest
    steps:
      - name: Grab Image
        run: |
          gh release download -R ta-vroom/alma-mkosi -p "alma_20260904.112.raw"
          sudo losetup -Pf alma_20260904.112.raw
          mkdir -p ./mnt
          sudo mount -o ro /dev/loop0p2 ./mnt
          cat ./mnt/etc/os-release
          # Cleanup
      - name: Cleanup
        run: |
          sudo umount ./mnt
          sudo losetup -D