name: ShellTest

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on: 
  workflow_dispatch:
  #push:

jobs:
  cache-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: | 
          sudo apt-get update && sudo apt-get install -y libguestfs-tools
      - name: Grab Image
        run: |
          gh release download -R ta-vroom/alma-mkosi -p "alma_20260904.112.raw"
          # Inspect partition contents
          guestfish --ro -a alma_20260904.112.raw -i ls /etc
          # Copy a specific file out
          guestfish --ro -a alma_20260904.112.raw -i download /etc/os-release ./os-release
          cat ./os-release